### PR TITLE
postgres db integration

### PR DESCRIPTION
**Pull request by YuliyaKVAS**
https://trello.com/c/olovxypu/27-am-node-integrate-db

### CODE REVIEW

**Comment by lessarea** [comment]
take a look at this please https://node-postgres.com/guides/project-structure

**Comment by YuliyaKVAS** [comment]
> take a look at this please https://node-postgres.com/guides/project-structure

do you mean I should change project structure?

**Comment by lessarea** [comment]
for now i'm ok with your implementation, but in the future please stick with structure suggested there

**Comment by lessarea** [comment]
more or less)

**Comment by lessarea** [comment]
ok

**Pull request merged**
